name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: install ninja
      run: sudo apt install ninja-build
    - name: Build with Gradle
      run: unset ANDROID_NDK_HOME && ./gradlew build
      
    - uses: actions/upload-artifact@v2
      with:
        name:  output
        path: app/outputs
